version: '3.8'

services:
  notification-service:
    build: .
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3003
    volumes:
      - ./db:/app/db
    restart: "no"  # Debug için restart kapalı
    # healthcheck:  # Debug için health check kapalı
    #   test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3003/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
