services:
  # vault:
  #   image: hashicorp/vault
  #   container_name: vault
  #   ports:
  #     - "8200:8200"
  #   volumes:
  #     - ./vault/config:/vault/config
  #     - ./vault/data:/vault/data
  #   cap_add:
  #     - IPC_LOCK
  #   command: server -config=/vault/config/vault.config.hcl
  #   environment:
  #     VAULT_ADDR: "http://127.0.0.1:8200" 
  #   networks:
  #     - internal-network
  api-gateway:
    build: 
      context: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - user-service
    env_file:
      - ./api-gateway/.env
    networks:
      - internal-network
    restart: always
  auth-service:
    build: 
      context: ./auth-service
    expose:
      - "3001"
    volumes:
      - ./auth-service/db:/app/db
    env_file:
      - ./auth-service/.env
    networks:
      - internal-network
    restart: always
  user-service:
    build:
      context: ./user-service
    expose:
      - "3002"
    volumes:
      - ./user-service/db:/app/db
    env_file:
      - ./user-service/.env
    networks:
      - internal-network
    restart: always
  elasticsearch :
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: "elasticsearch"
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx2048m
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - internal-network
    mem_limit: 2g
    restart: always

  logstash :
    image: docker.elastic.co/logstash/logstash:8.14.0
    container_name: "logstash"
    ports:
      - "5044:5044"
    volumes:
    - /home/ekose/Desktop/FT_PINPON/elastic-search/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - internal-network
    depends_on:
      - elasticsearch
    mem_limit: 2g
    restart: always

  kibana : 
    image:  docker.elastic.co/kibana/kibana:8.14.0
    container_name: "kibana"
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - internal-network
    mem_limit: 2g
    restart: always

volumes:
  es_data:

networks:
  internal-network:
    driver: bridge