CREATE TABLE IF NOT EXISTS messages(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	sender_id INTEGER NOT NULL,
	recv_id INTEGER NOT NULL,
	content TEXT NOT NULL,
	status varchar(10) DEFAULT "DELIVERID",
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

